version: '3.9'

services:
  api:
    build: .
    container_name: sgpi_api
    ports:
      - "8009:8009"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@24.199.108.245:5445/sgpi
      - SECRET_KEY=supersecret
      # MinIO
      - MINIO_ENDPOINT=http://minio.labtecs.com.br:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=false
      - MINIO_BUCKET=sgpi-files
    # Dev-only: autogerar migrations (se quiser)
    # - AUTO_MIGRATE=1
    depends_on:
      - postgres
      - minio
    networks:
      - nginx_proxy     # para o Nginx/NPM resolver "api"
      - backend         # rede interna para falar com o Postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: sgpi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # Se quiser acessar de fora para debug (opcional):
    ports:
      - "5445:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sgpi"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
  backend:
    driver: bridge

volumes:
  pgdata:
